openapi: 3.0.3
info:
  title: Bitly clone API
  version: 1.0.0

servers:
  - url: http://localhost:3000
    description: Local server
apis: ["./routes/*.js"]

tags:
  - name: Auth
    description: Authentication
  - name: Urls
    description: Urls
  - name: Statistics
    description: Statistics

paths:
  /auth/register:
    post:
      tags:
        - Auth
      summary: Register a new user
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/User"
      responses:
        "201":
          description: User created
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/User"
        "400":
          description: Bad request
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
        "409":
          description: User already exists
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
  /auth/login:
    post:
      tags:
        - Auth
      summary: Login a user
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/LoginRequest"
      responses:
        "200":
          description: User logged in
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/LoginResponse"
        "400":
          description: Bad request
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
        "401":
          description: Unauthorized
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
  /urls/shorten:
    post:
      security:
        - BearerAuth: []
      tags:
        - Urls
      summary: Shorten a url
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/ShortenRequest"
      responses:
        "201":
          description: Url shortened
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ShortenResponse"
        "400":
          description: Bad request
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
        "401":
          description: Unauthorized
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
  /{code}:
    get:
      summary: Redirect to the original url
      parameters:
        - in: path
          name: code
          schema:
            type: string
          required: true
          description: The code of the url
      responses:
        "302":
          description: Redirect to the original url
        "404":
          description: Url not found
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
  /urls/userUrls:
    get:
      security:
        - BearerAuth: []
      tags:
        - Urls
      summary: Get all urls
      parameters:
        - in: query
          name: username
          schema:
            type: string
          required: true
          example: "test@gmail.com"
          description: The username (email) of the user
      responses:
        "200":
          description: Urls found
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/UserUrls"
        "401":
          description: Unauthorized
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
        "404":
          description: Urls not found
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
  /urls/{code}:
    get:
      security:
        - BearerAuth: []
      tags:
        - Urls
      summary: Get a url
      parameters:
        - in: path
          name: code
          schema:
            type: string
          required: true
          description: The code of the url
      responses:
        "200":
          description: Url found
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/UserUrls"
        "401":
          description: Unauthorized
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
        "404":
          description: Url not found
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
  /stats/groupByDate:
    get:
      security:
        - BearerAuth: []
      tags:
        - Statistics
      summary: Get stats
      parameters:
        - in: query
          name: code
          schema:
            type: string
          required: false
          description: The code of the url
        
          
      responses:
        "200":
          description: Stats found
          content:
            application/json:
              type: Object
        "401":
          description: Unauthorized
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
        "404":
          description: Stats not found
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
components:
  schemas:
    User:
      type: object
      required:
        - email
        - password
        - firstName
        - lastName
      properties:
        email:
          type: string
          format: email
        password:
          type: string
          format: password
        firstName:
          type: string
        lastName:
          type: string
      example:
        email: "test@gmail.com"
        password: "1234"
        firstName: "John"
        lastName: "Doe"
    LoginRequest:
      type: object
      required:
        - email
        - password
      properties:
        email:
          type: string
          format: email
        password:
          type: string
          format: password
      example:
        email: "test@gmail.com"
        password: "1234"

    Error:
      type: object
      required:
        - message
      properties:
        message:
          type: string
    LoginResponse:
      type: object
      required:
        - token
      properties:
        token:
          type: string
    ShortenRequest:
      type: object
      required:
        - url
        - username
      properties:
        longUrl:
          type: string
          format: url
        username:
          type: string
      example:
        longUrl: "https://www.google.com"
        username: "test@gmail.com"
    ShortenResponse:
      type: object
      required:
        - shortUrl
      properties:
        shortUrl:
          type: string
          format: url
      example:
        shortUrl: "http://localhost:3000/1"
    UserUrls:
      type: object
      required:
        - code
        - longUrl
        - clicks
      properties:
        longUrl:
          type: string
          format: url
        clicks:
          type: integer
        code:
          type: string
      example:
        code: "abc"
        longUrl: "https://www.google.com"
        clicks: 0
  securitySchemes:
    BearerAuth:
      scheme: bearer
      bearerFormat: JWT
      type: apiKey
      in: header
      name: Authorization